export const countries = [
  { name: "🇬🇭 Ghana", code: "GH" },
  { name: "🇳🇬 Nigeria", code: "NG" },
  { name: "🇰🇪 Kenya", code: "KE" },
  { name: "🇿🇦 South Africa", code: "ZA" },
  { name: "🇺🇬 Uganda", code: "UG" },
  { name: "🇨🇲 Cameroon", code: "CM" },
  { name: "🇿🇲 Zambia", code: "ZM" },
  { name: "🇺🇸 United States", code: "US" },
  { name: "🇨🇦 Canada", code: "CA" },
  { name: "🇬🇧 United Kingdom", code: "GB" },
  { name: "🇩🇪 Germany", code: "DE" },
  { name: "🇫🇷 France", code: "FR" },
  { name: "🇮🇳 India", code: "IN" },
  { name: "🇨🇳 China", code: "CN" },
  { name: "🇯🇵 Japan", code: "JP" },
];
